select * from question_answer

insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ciencias Sociales',1,56);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ciencias Naturales',0,56);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La Física',0,56);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Química',0,56);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Las Humanidades',1,57);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La Naturaleza',0,57);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Análisis',0,57);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Progreso',0,57);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'No, no lo usa',1,58);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Si, si lo usa',0,58);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ambas la usan.',0,58);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Nignuna',0,58);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'El funcionamiento de las Sociedades',1,59);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La Cultura',0,59);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Las tradiciones',0,59);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La Geografía',0,59);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ciencias Naturales',1,60);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La economía',0,60);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La semiología',0,60);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'La Arqueología',0,60);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Políticas y la sociología',1,61);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Culturas y tradiciones',0,61);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Biología y Química',0,61);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ninguna es correcta',0,61);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Mundial',1,62);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Nacional',0,62);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Para Nadie',0,62);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Centro América',0,62);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',1,63);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Naturaleza',0,63);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Seres vivos',0,63);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Aspectos físicos',0,63);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Son abarcadas por el hombre.',1,64);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Leyes sociales',0,64);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Estudio de la Naturaleza',0,64);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Nignuna ',0,64);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Antropología',1,65);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',0,65);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Derecho',0,65);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Economía',0,65);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Etnología',1,66);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Antropología',0,66);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Derecho',0,66);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Economía',0,66);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Sociología',1,67);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',0,67);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Antropología',0,67);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Etnología',0,67);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',1,68);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Sociología',0,68);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Etnología',0,68);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Derecho',0,68);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Economía',1,69);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Derecho',0,69);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Sociología',0,69);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',0,69);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Interculturalidad',1,70);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Lo social',0,70);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Lo Natural',0,70);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Lo Personal',0,70);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Comunicación',1,71);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Lenguaje',0,71);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Sociedad',0,71);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Culturas y tradiciones',0,71);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Pedagogía',1,72);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Culturas y tradiciones',0,72);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Antropología',0,72);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Derecho',0,72);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Psicología',1,73);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Pedagogía',0,73);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Antropología',0,73);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Historia',0,73);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Estudia los sistemas vivos.',1,74);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Estudia los  números',0,74);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Estudia la Naturaleza',0,74);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ninguna es correcta',0,74);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ciencias Humanas',1,75);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Ciencias Naturales',0,75);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Física',0,75);
insert into question_answer (created_at,created_by,company_id,is_active,name,is_correct,question_id) values (getdate(),1,1,1,'Matemáticas',0,75);
