/*
SQL
  DML = manipulacion
    SELECT
    UPDATE    //WHERE ORDER BY
    DELETE
    
  DDL = DEFINICION
    CREATE
    DROP
    ALTER
    
  CDL = CONTROL
    USUARIOS // UNA HOJA ES EQUIVALENTE A UNA TABLA EN EXCEL    
*/
CREATE TABLE CLIENTE(
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(50),
  NIT VARCHAR2(10),
  TELEFONO VARCHAR2(8),
  DIRECCION VARCHAR2(50)
);

CREATE TABLE TIPOCLIENTE(
  ID NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(50)
);

INSERT INTO CLIENTE VALUES('1','Juan','3423-5','34509733','Retalhuleu zona 1');
INSERT INTO CLIENTE VALUES('2','Pedro','9384-5','89347612','zona 4');
INSERT INTO CLIENTE VALUES('3','Mario','1230-5','34406448','La Galera');
INSERT INTO CLIENTE VALUES('4','Rodrigo','8374-5','45981233','Los mangales');
INSERT INTO CLIENTE VALUES('5','Maria','2738-5','53709733','zona 5');

--ORDER BY
SELECT * FROM CLIENTE ORDER BY NOMBRE DESC;

--WHERE ATRIBUTO
SELECT * FROM CLIENTE WHERE ID = 3;
SELECT * FROM CLIENTE WHERE ID IN(2,3); --CONSULTA UN DETERMINADO NUMEROS DE ID DE TODOS LOS DATOS
SELECT * FROM CLIENTE WHERE ID NOT IN(2,3); --CONSULTA UN DETERMINADO NUMEROS DE ID DE TODOS LOS DATOS SIN INCLUIR EL 2 Y 3
SELECT * FROM CLIENTE WHERE ID > 4; --CONSULTA TODOS LOS REGISTROS MAYORES A 4
SELECT * FROM CLIENTE WHERE ID < 4; --CONSULTA TODOS LOS REGISTROS MENORES A 4
SELECT * FROM CLIENTE WHERE ID >= 4; --CONSULTA TODOS LOS REGISTROS MAYORES E IGUAL A 4
SELECT * FROM CLIENTE WHERE ID <= 4; --CONSULTA TODOS LOS REGISTROS MENORES E IGUAL A 4
SELECT * FROM CLIENTE WHERE ID BETWEEN 2 AND 4; --CONSULTA UN RANGO DE REGISTROS
SELECT * FROM CLIENTE WHERE ID BETWEEN 3 AND 5 OR ID = 1; --CONSULTA UN RANGO DE REGISTROS Y TAMBIEN EL 1
SELECT * FROM CLIENTE WHERE ID >= 3 AND ID <= 5 OR ID = 1;

--UPDATE
UPDATE CLIENTE SET DIRECCION = 'REU' WHERE ID IN(1,2);
UPDATE CLIENTE SET DIRECCION = 'MAZATE' WHERE ID IN(3,5);
UPDATE CLIENTE SET DIRECCION = 'XELA' WHERE ID = 4;

--LIKE
-- CONVERSION DE DATOS UPPER(ATRIBUTO) Y LOWER(ATRIBUTO)
SELECT * FROM CLIENTE WHERE UPPER(DIRECCION) LIKE 'R%'; --BUSCA LA PALABRA QUE INICIA CON R Y POSTERIOMENTE VA A CONTENER CUALQUIER CARACTER ESO SE LO DECIMOS ATRAVES DEL %
SELECT * FROM CLIENTE WHERE DIRECCION LIKE '%TE%'; --BUSCA CUALQUIER PALABRA QUE CONTENGA LA PALABRA TE HAY QUE TENER CONSIDERACIONES LAS MAYUS Y MINUSCULAS
SELECT * FROM CLIENTE WHERE DIRECCION LIKE '%A'; -- BUSCA CUALQUIER VALOR QUE FINALICE CON LA LETRA A

